from .adapter import OpenAiNnrpAdapter
from .benchmark import BenchmarkConfig, run_benchmark
from .embedded import (
    EmbeddedTcpServerConfig,
    create_embedded_openai_adapter,
    load_serving_chat_factory,
    run_embedded_tcp_server,
    run_embedded_tcp_server_sync,
    serve_embedded_tcp_listener,
)
from .nnrp_runtime import (
    EmittedNnrpResult,
    NnrpFrameContext,
    decode_profile_event,
    decode_submit_profile_request,
    emit_openai_profile_results,
    emit_profile_event,
    encode_profile_event,
    frame_context_from_submit,
    handle_openai_profile_submit,
    serve_openai_profile_session,
)
from .profile import (
    OPENAI_COMPATIBLE_PROFILE,
    OPENAI_COMPATIBLE_SCHEMA_VERSION,
    OpenAiNnrpCapabilityDocument,
    OpenAiNnrpError,
    OpenAiNnrpRequest,
    ProfileEvent,
    build_cancelled_event,
    build_diagnostics_event,
    build_error_event,
    build_text_delta_event,
    build_usage_event,
)
from .vllm_backend import VllmBackend
from .vllm_factory import create_chat_completion_request, create_vllm_backend

__all__ = [
    "OPENAI_COMPATIBLE_PROFILE",
    "OPENAI_COMPATIBLE_SCHEMA_VERSION",
    "BenchmarkConfig",
    "EmittedNnrpResult",
    "EmbeddedTcpServerConfig",
    "NnrpFrameContext",
    "OpenAiNnrpAdapter",
    "OpenAiNnrpCapabilityDocument",
    "OpenAiNnrpError",
    "OpenAiNnrpRequest",
    "ProfileEvent",
    "VllmBackend",
    "build_cancelled_event",
    "build_diagnostics_event",
    "build_error_event",
    "build_text_delta_event",
    "build_usage_event",
    "create_chat_completion_request",
    "create_embedded_openai_adapter",
    "create_vllm_backend",
    "decode_profile_event",
    "decode_submit_profile_request",
    "emit_openai_profile_results",
    "emit_profile_event",
    "encode_profile_event",
    "frame_context_from_submit",
    "handle_openai_profile_submit",
    "load_serving_chat_factory",
    "run_benchmark",
    "run_embedded_tcp_server",
    "run_embedded_tcp_server_sync",
    "serve_embedded_tcp_listener",
    "serve_openai_profile_session",
]
