from __future__ import annotations

import argparse
from pathlib import Path

from vllm_nnrp_adapter.vllm_compat import render_vllm_compatibility_table

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "doc" / "vllm-compatibility.md"


def generated_content() -> str:
    return "<!-- Generated by scripts/generate_vllm_compatibility_table.py. -->\n\n" + render_vllm_compatibility_table()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generated_content()
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != content:
            raise SystemExit(f"{OUTPUT_PATH} is stale; run {Path(__file__).name}")
        return 0
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
